-- Create volatile tables for variables
CREATE VOLATILE TABLE VarTable (
    rid INTEGER,
    execid INTEGER
) ON COMMIT PRESERVE ROWS;


-- Insert initial values
INSERT INTO VarTable (rid, execid)
SELECT COALESCE(MAX(r.RUN_ID), 0) + 1, COALESCE(MAX(t.EXEC_ID), 0) + 1
FROM TCH.T_SUIV_RUN AS r, TCH.T_SUIV_TRMT AS t;


-- Insert into TCH.T_SUIV_RUN
INSERT INTO TCH.T_SUIV_RUN (RUN_ID, RUN_STRT_DTTM, RUN_END_DTTM, RUN_STTS_CD)
SELECT rid, CURRENT_TIMESTAMP(0), NULL, 'ENC'
FROM VarTable;

-- Insert into TCH.T_SUIV_TRMT
INSERT INTO TCH.T_SUIV_TRMT (EXEC_ID, RUN_ID, SCRPT_NAME, EXEC_STRT_DTTM, EXEC_END_DTTM, EXEC_STTS_CD)
SELECT execid, rid, 'run_tpt.sh', CURRENT_TIMESTAMP(0), NULL, 'ENC'
FROM VarTable;

DROP TABLE VarTable;