SELECT * FROM dbc.Databases WHERE DatabaseName = 'STG';
.IF ACTIVITYCOUNT <> 0 THEN .GOTO SKIP_STG;
CREATE DATABASE STG from DBC as perm=1000000000;
GRANT ALL PRIVILEGES ON STG TO DBC WITH GRANT OPTION;
.LABEL SKIP_STG

SELECT * FROM dbc.Databases WHERE DatabaseName = 'WRK';
.IF ACTIVITYCOUNT <> 0 THEN .GOTO SKIP_WRK;
CREATE DATABASE WRK from DBC as perm=1000000000;
GRANT ALL PRIVILEGES ON WRK TO DBC WITH GRANT OPTION;
.LABEL SKIP_WRK

SELECT * FROM dbc.Databases WHERE DatabaseName = 'SOC';
.IF ACTIVITYCOUNT <> 0 THEN .GOTO SKIP_SOC;
CREATE DATABASE SOC from DBC as perm=1000000000;
GRANT ALL PRIVILEGES ON SOC TO DBC WITH GRANT OPTION;
.LABEL SKIP_SOC

SELECT * FROM dbc.Databases WHERE DatabaseName = 'TCH';
.IF ACTIVITYCOUNT <> 0 THEN .GOTO SKIP_TCH;
CREATE DATABASE TCH from DBC as perm=1000000000;
GRANT ALL PRIVILEGES ON TCH TO DBC WITH GRANT OPTION;
.LABEL SKIP_TCH