-- Create volatile tables for variables
CREATE VOLATILE TABLE VarTable (
    rid INTEGER,
    execid INTEGER
) ON COMMIT PRESERVE ROWS;

-- Insert initial values
INSERT INTO VarTable (rid, execid)
SELECT COALESCE(MAX(r.RUN_ID), 0), COALESCE(MAX(t.EXEC_ID), 0)
FROM TCH.T_SUIV_RUN AS r, TCH.T_SUIV_TRMT AS t;

-- Increment rid and execid
UPDATE VarTable
SET execid = execid + 1;

-- Insert into TCH.T_SUIV_TRMT
INSERT INTO TCH.T_SUIV_TRMT (EXEC_ID, RUN_ID, SCRPT_NAME, EXEC_STRT_DTTM, EXEC_END_DTTM, EXEC_STTS_CD)
SELECT execid, rid, 'insert_to_wrk_from_stg.sql', CURRENT_TIMESTAMP(0), NULL, 'ENC'
FROM VarTable;

-- Delete and insert into WRK.R_ROOM
DELETE FROM WRK.R_ROOM;

INSERT INTO WRK.R_ROOM (ROOM_NUM, ROOM_NAME, FLOR_NUM, BULD_NAME, ROOM_TYP, ROOM_DAY_RATE, CRTN_DT, EXEC_ID)
SELECT
    s.ROOM_NUM,
    s.ROOM_NAME,
    s.FLOR_NUM,
    s.BULD_NAME,
    s.ROOM_TYP,
    s.ROOM_DAY_RATE,
    s.CRTN_DT,
    s.EXEC_ID
FROM (
    SELECT
        NO_CHAMBRE AS ROOM_NUM,
        NOM_CHAMBRE AS ROOM_NAME,
        NO_ETAGE AS FLOR_NUM,
        NOM_BAT AS BULD_NAME,
        TYPE_CHAMBRE AS ROOM_TYP,
        PRIX_JOUR AS ROOM_DAY_RATE,
        DT_CREATION AS CRTN_DT,
        (SELECT execid FROM VarTable) AS EXEC_ID
    FROM
        STG.CHAMBRE
) AS s;

-- Create volatile table for ID_TABLE
CREATE VOLATILE TABLE ID_TABLE (
    med_id INTEGER,
    part_id INTEGER
) ON COMMIT PRESERVE ROWS;

-- Insert initial values into ID_TABLE
INSERT INTO ID_TABLE (med_id, part_id)
SELECT COALESCE(MAX(MEDC_ID), 0), COALESCE(MAX(PART_ID), 0)
FROM SOC.R_MEDC, SOC.R_PART;

-- Delete and insert into WRK.R_MEDC
DELETE FROM WRK.R_MEDC;

INSERT INTO WRK.R_MEDC (MEDC_ID, MEDC_CD, MEDC_NAME, MEDC_COND, MEDC_CATG, MEDC_BRND, EXEC_ID)
SELECT
    s.MEDC_ID,
    s.MEDC_CD,
    s.MEDC_NAME,
    s.MEDC_COND,
    s.MEDC_CATG,
    s.MEDC_BRND,
    s.EXEC_ID
FROM (
    SELECT
        (SELECT med_id FROM ID_TABLE) + ROW_NUMBER() OVER (ORDER BY CD_MEDICAMENT, CATG_MEDICAMENT, MARQUE_FABRI) AS MEDC_ID,
        CD_MEDICAMENT AS MEDC_CD,
        NOM_MEDICAMENT AS MEDC_NAME,
        CONDIT_MEDICAMENT AS MEDC_COND,
        CATG_MEDICAMENT AS MEDC_CATG,
        MARQUE_FABRI AS MEDC_BRND,
        (SELECT execid FROM VarTable) AS EXEC_ID
    FROM
        STG.MEDICAMENT
) AS s;

-- Delete and insert into WRK.R_PART (first part)
DELETE FROM WRK.R_PART;

INSERT INTO WRK.R_PART (PART_ID, SRC_ID, SRC_TYP)
SELECT
    s.PART_ID,
    s.SRC_ID,
    s.SRC_TYP
FROM (
    SELECT
        (SELECT part_id FROM ID_TABLE) + ROW_NUMBER() OVER (ORDER BY ID_PERSONNEL, FONCTION_PERSONNEL) AS PART_ID,
        ID_PERSONNEL AS SRC_ID,
        FONCTION_PERSONNEL AS SRC_TYP
    FROM
        STG.PERSONNEL
) AS s;

-- Update ID_TABLE
UPDATE ID_TABLE
SET part_id = (SELECT MAX(PART_ID) FROM WRK.R_PART);

-- Delete and insert into WRK.R_PART (second part)

INSERT INTO WRK.R_PART (PART_ID, SRC_ID, SRC_TYP)
SELECT
    s.PART_ID,
    s.SRC_ID,
    s.SRC_TYP
FROM (
    SELECT
        (SELECT part_id FROM ID_TABLE) + ROW_NUMBER() OVER (ORDER BY ID_PATIENT, 'Patient') AS PART_ID,
        ID_PATIENT AS SRC_ID,
        'Patient' AS SRC_TYP
    FROM
        STG.PATIENT
) AS s;

-- Delete and insert into WRK.O_STFF
DELETE FROM WRK.O_STFF;

INSERT INTO WRK.O_STFF (PART_ID, WORK_STRT_DTTM, WORK_END_DTTM, WORK_END_RESN, EXEC_ID)
SELECT
    s.PART_ID,
    s.WORK_STRT_DTTM,
    s.WORK_END_DTTM,
    s.WORK_END_RESN,
    s.EXEC_ID
FROM (
    SELECT
        r.PART_ID AS PART_ID,
        TS_DEBUT_ACTIVITE AS WORK_STRT_DTTM,
        TS_FIN_ACTIVITE AS WORK_END_DTTM,
        RAISON_FIN_ACTIVITE AS WORK_END_RESN,
        (SELECT execid FROM VarTable) AS EXEC_ID
    FROM
        STG.PERSONNEL AS p
    INNER JOIN
        WRK.R_PART AS r
    ON
        p.ID_PERSONNEL = r.SRC_ID
        AND p.FONCTION_PERSONNEL = r.SRC_TYP
) AS s;

-- Delete and insert into WRK.O_INDIV (first part)
DELETE FROM WRK.O_INDIV;

INSERT INTO WRK.O_INDIV (PART_ID, INDV_NAME, INDIV_FIRS_NAME, INDV_STTS_CD, CRTN_DTTM, UPDT_DTTM, EXEC_ID)
SELECT
    s.PART_ID,
    s.INDV_NAME,
    s.INDIV_FIRS_NAME,
    s.INDV_STTS_CD,
    s.CRTN_DTTM,
    s.UPDT_DTTM,
    s.EXEC_ID
FROM (
    SELECT
        r.PART_ID AS PART_ID,
        NOM_PERSONNEL AS INDV_NAME,
        PRENOM_PERSONNEL AS INDIV_FIRS_NAME,
        CD_STATUT_PERSONNEL AS INDV_STTS_CD,
        TS_CREATION_PERSONNEL AS CRTN_DTTM,
        TS_MAJ_PERSONNEL AS UPDT_DTTM,
        (SELECT execid FROM VarTable) AS EXEC_ID
    FROM
        STG.PERSONNEL AS p
    INNER JOIN
        WRK.R_PART AS r
    ON
        p.ID_PERSONNEL = r.SRC_ID
        AND p.FONCTION_PERSONNEL = r.SRC_TYP
) AS s;

-- Delete and insert into WRK.O_INDIV (second part)

INSERT INTO WRK.O_INDIV (PART_ID, INDV_NAME, INDIV_FIRS_NAME, INDV_STTS_CD, CRTN_DTTM, UPDT_DTTM, EXEC_ID, BIRT_DT, BIRT_CITY, BIRT_CNTR, WRKL_NUM)
SELECT
    s.PART_ID,
    s.INDV_NAME,
    s.INDIV_FIRS_NAME,
    s.INDV_STTS_CD,
    s.CRTN_DTTM,
    s.UPDT_DTTM,
    s.EXEC_ID,
    s.BIRT_DT,
    s.BIRT_CITY,
    s.BIRT_CNTR,
    s.WRKL_NUM
FROM (
    SELECT
        r.PART_ID AS PART_ID,
        NOM_PATIENT AS INDV_NAME,
        PRENOM_PATIENT AS INDIV_FIRS_NAME,
        'Actif' AS INDV_STTS_CD,
        TS_CREATION_PATIENT AS CRTN_DTTM,
        TS_MAJ_PATIENT AS UPDT_DTTM,
        (SELECT execid FROM VarTable) AS EXEC_ID,
        DT_NAISS AS BIRT_DT,
        VILLE_NAISS AS BIRT_CITY,
        PAYS_NAISS AS BIRT_CNTR,
        NUM_SECU AS WRKL_NUM
    FROM
        STG.PATIENT AS p
    INNER JOIN
        WRK.R_PART AS r
    ON
        p.ID_PATIENT = r.SRC_ID
        AND 'PATIENT' = r.SRC_TYP
) AS s;

-- Delete and insert into WRK.O_TELP
DELETE FROM WRK.O_TELP;

INSERT INTO WRK.O_TELP (PART_ID, CNTR_CD, TELP_NUM, STRT_VALD_DTTM, END_VALD_DTTM, EXEC_ID)
SELECT
    s.PART_ID,
    s.CNTR_CD,
    s.TELP_NUM,
    s.STRT_VALD_DTTM,
    s.END_VALD_DTTM,
    s.EXEC_ID
FROM (
    SELECT
        r.PART_ID AS PART_ID,
        IND_PAYS_NUM_TELP AS CNTR_CD,
        NUM_TELEPHONE AS TELP_NUM,
        TS_CREATION_PATIENT AS STRT_VALD_DTTM,
        TS_MAJ_PATIENT AS END_VALD_DTTM,
        (SELECT execid FROM VarTable) AS EXEC_ID
    FROM
        STG.PATIENT AS p
    INNER JOIN
        WRK.R_PART AS r
    ON
        p.ID_PATIENT = r.SRC_ID
        AND 'PATIENT' = r.SRC_TYP
) AS s;

-- Delete and insert into WRK.O_ADDR
DELETE FROM WRK.O_ADDR;

INSERT INTO WRK.O_ADDR (PART_ID, STRT_NUM, STRT_DSC, COMP_STRT, POST_CD, CITY_NAME, CNTR_NAME, STRT_VALD_DTTM, END_VALD_DTTM, EXEC_ID)
SELECT
    s.PART_ID,
    s.STRT_NUM,
    s.STRT_DSC,
    s.COMP_STRT,
    s.POST_CD,
    s.CITY_NAME,
    s.CNTR_NAME,
    s.STRT_VALD_DTTM,
    s.END_VALD_DTTM,
    s.EXEC_ID
FROM (
    SELECT
        r.PART_ID AS PART_ID,
        NUM_VOIE AS STRT_NUM,
        DSC_VOIE AS STRT_DSC,
        CMPL_VOIE AS COMP_STRT,
        CD_POSTAL AS POST_CD,
        VILLE AS CITY_NAME,
        PAYS AS CNTR_NAME,
        TS_CREATION_PATIENT AS STRT_VALD_DTTM,
        TS_MAJ_PATIENT AS END_VALD_DTTM,
        (SELECT execid FROM VarTable) AS EXEC_ID
    FROM
        STG.PATIENT AS p
    INNER JOIN
        WRK.R_PART AS r
    ON
        p.ID_PATIENT = r.SRC_ID
        AND 'PATIENT' = r.SRC_TYP
) AS s;

-- Delete and insert into WRK.O_TRET
DELETE FROM WRK.O_TRET;

INSERT INTO WRK.O_TRET (TRET_ID, MEDC_ID, MEDC_QTY, DOSG_DSC, CONS_ID, TRET_CRTN_DTTM, EXEC_ID)
SELECT
    s.TRET_ID,
    s.MEDC_ID,
    s.MEDC_QTY,
    s.DOSG_DSC,
    s.CONS_ID,
    s.TRET_CRTN_DTTM,
    s.EXEC_ID
FROM (
    SELECT
        ID_TRAITEMENT AS TRET_ID,
        m.MEDC_ID AS MEDC_ID,
        QTE_MEDICAMENT AS MEDC_QTY,
        DSC_POSOLOGIE AS DOSG_DSC,
        ID_CONSULT AS CONS_ID,
        TS_CREATION_TRAITEMENT AS TRET_CRTN_DTTM,
        (SELECT execid FROM VarTable) AS EXEC_ID
    FROM
        STG.TRAITEMENT AS t
    INNER JOIN
        WRK.R_MEDC AS m
    ON
        t.CD_MEDICAMENT = m.MEDC_CD
        AND t.CATG_MEDICAMENT = m.MEDC_CATG
        AND t.MARQUE_FABRI = m.MEDC_BRND
) AS s;

-- Delete and insert into WRK.O_CONS
DELETE FROM WRK.O_CONS;

INSERT INTO WRK.O_CONS (CONS_ID, STFF_ID, PATN_ID, CONS_STRT_DTTM, CONS_END_DTTM, PATN_WEGH, PATN_TEMP, TEMP_UNIT, BLD_PRSS, PATH_DSC, DIBT_IND, TRET_ID, HOSP_IND, EXEC_ID)
SELECT
    s.CONS_ID,
    s.STFF_ID,
    s.PATN_ID,
    s.CONS_STRT_DTTM,
    s.CONS_END_DTTM,
    s.PATN_WEGH,
    s.PATN_TEMP,
    s.TEMP_UNIT,
    s.BLD_PRSS,
    s.PATH_DSC,
    s.DIBT_IND,
    s.TRET_ID,
    s.HOSP_IND,
    s.EXEC_ID
FROM (
    SELECT
        ID_CONSULT AS CONS_ID,
        ID_PERSONNEL AS STFF_ID,
        ID_PATIENT AS PATN_ID,
        CASE WHEN TS_DEBUT_CONSULT < TS_FIN_CONSULT THEN TS_DEBUT_CONSULT ELSE TS_FIN_CONSULT END AS CONS_STRT_DTTM,
        CASE WHEN TS_DEBUT_CONSULT < TS_FIN_CONSULT THEN TS_FIN_CONSULT ELSE TS_DEBUT_CONSULT END AS CONS_END_DTTM,
        POIDS_PATIENT AS PATN_WEGH,
        TEMP_PATIENT AS PATN_TEMP,
        UNIT_TEMP AS TEMP_UNIT,
        TENSION_PATIENT AS BLD_PRSS,
        DSC_PATHO AS PATH_DSC,
        CASE WHEN INDIC_DIABETE = 'True' THEN 1 ELSE 0 END AS DIBT_IND,
        ID_TRAITEMENT AS TRET_ID,
        CASE WHEN INDIC_HOSPI = 'True' THEN 1 ELSE 0 END AS HOSP_IND,
        (SELECT execid FROM VarTable) AS EXEC_ID
    FROM
        STG.CONSULTATION
) AS s;

-- Delete and insert into WRK.O_HOSP
DELETE FROM WRK.O_HOSP;

INSERT INTO WRK.O_HOSP (HOSP_ID, CONS_ID, ROOM_NUM, HOSP_STRT_DTTM, HOSP_END_DTTM, HOSP_FINL_RATE, STFF_ID, EXEC_ID)
SELECT
    s.HOSP_ID,
    s.CONS_ID,
    s.ROOM_NUM,
    s.HOSP_STRT_DTTM,
    s.HOSP_END_DTTM,
    s.HOSP_FINL_RATE,
    s.STFF_ID,
    s.EXEC_ID
FROM (
    SELECT
        ID_HOSPI AS HOSP_ID,
        ID_CONSULT AS CONS_ID,
        NO_CHAMBRE AS ROOM_NUM,
        CASE WHEN TS_DEBUT_HOSPI < TS_FIN_HOSPI THEN TS_DEBUT_HOSPI ELSE TS_FIN_HOSPI END AS HOSP_STRT_DTTM,
        CASE WHEN TS_DEBUT_HOSPI < TS_FIN_HOSPI THEN TS_FIN_HOSPI ELSE TS_DEBUT_HOSPI END AS HOSP_END_DTTM,
        COUT_HOSPI AS HOSP_FINL_RATE,
        ID_PERSONNEL_RESP AS STFF_ID,
        (SELECT execid FROM VarTable) AS EXEC_ID
    FROM
        STG.HOSPITALISATION
) AS s;

-- Drop the volatile table
DROP TABLE VarTable;
DROP TABLE ID_TABLE;
